# Generated by Django 2.2.5 on 2019-09-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzashop',
            name='address',
            field=models.CharField(max_length=30, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='pizzashop',
            name='logo',
            field=models.ImageField(upload_to='pizzashop_logo/', verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='pizzashop',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='pizzashop',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
    ]
